### ISSUE TITLE
Wrong version of LemurProject

### ISSUE THREAD

**Issue by jbeuckm** [claritylab/sirius#69]
```
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
```
How can I find out which version of Lemur and install the right one? Here is the console when I run the "speed of light" test:

```
Query str: query=what%20is%20the%20speed%20of%20light

+++++ Analyzing question (2015-05-01 11:01:32) +++++
Normalization: what be the speed of light

Answer types:
NErate->NEspeed

Interpretations:
Property: SPEED
Target: light

Predicates:
-

+++++ Generating queries (2015-05-01 11:01:36) +++++
Query strings:
speed light
("speed of light" OR "light speed")
"light" speed light
"is the speed of light"
"the speed of light is"

+++++ Searching (2015-05-01 11:01:36) +++++
Exception in thread "Thread-18" java.lang.UnsupportedClassVersionError: lemurproject/indri/QueryEnvironment : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
	at info.ephyra.search.searchers.IndriKM.doSearch(IndriKM.java:200)
	at info.ephyra.search.searchers.Searcher.run(Searcher.java:41)
Exception in thread "Thread-22" java.lang.UnsupportedClassVersionError: lemurproject/indri/QueryEnvironment
	at info.ephyra.search.searchers.IndriKM.doSearch(IndriKM.java:200)
	at info.ephyra.search.searchers.Searcher.run(Searcher.java:41)
Exception in thread "Thread-21" java.lang.UnsupportedClassVersionError: lemurproject/indri/QueryEnvironment
	at info.ephyra.search.searchers.IndriKM.doSearch(IndriKM.java:200)
	at info.ephyra.search.searchers.Searcher.run(Searcher.java:41)
Exception in thread "Thread-20" java.lang.UnsupportedClassVersionError: lemurproject/indri/QueryEnvironment
	at info.ephyra.search.searchers.IndriKM.doSearch(IndriKM.java:200)
	at info.ephyra.search.searchers.Searcher.run(Searcher.java:41)
Exception in thread "Thread-19" java.lang.UnsupportedClassVersionError: lemurproject/indri/QueryEnvironment
	at info.ephyra.search.searchers.IndriKM.doSearch(IndriKM.java:200)
	at info.ephyra.search.searchers.Searcher.run(Searcher.java:41)
```

**Comment by jbeuckm** [comment]
I updated to 14.04 and started over with the Sirius setup. I see a more detailed error now:
```
+++++ Searching (2015-05-26 15:14:21) +++++
OpenJDK Server VM warning: You have loaded library /home/cougar/sirius/sirius-application/question-answer/lib/search/libindri_jni.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Exception in thread "Thread-18" Exception in thread "Thread-19" Exception in thread "Thread-20" Exception in thread "Thread-21" Exception in thread "Thread-22" java.lang.NoClassDefFoundError: Could not initialize class lemurproject.indri.indriJNI
	at lemurproject.indri.QueryEnvironment.<init>(QueryEnvironment.java:39)
	at info.ephyra.search.searchers.IndriKM.doSearch(IndriKM.java:200)
	at info.ephyra.search.searchers.Searcher.run(Searcher.java:41)
java.lang.UnsatisfiedLinkError: /home/cougar/sirius/sirius-application/question-answer/lib/search/libindri_jni.so: /home/cougar/sirius/sirius-application/question-answer/lib/search/libindri_jni.so: wrong ELF class: ELFCLASS64 (Possible cause: architecture word width mismatch)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1880)
	at java.lang.Runtime.loadLibrary0(Runtime.java:849)
	at java.lang.System.loadLibrary(System.java:1088)
	at lemurproject.indri.indriJNI.<clinit>(indriJNI.java:109)
	at lemurproject.indri.QueryEnvironment.<init>(QueryEnvironment.java:39)
	at info.ephyra.search.searchers.IndriKM.doSearch(IndriKM.java:200)
	at info.ephyra.search.searchers.Searcher.run(Searcher.java:41)
java.lang.NoClassDefFoundError: Could not initialize class lemurproject.indri.indriJNI
	at lemurproject.indri.QueryEnvironment.<init>(QueryEnvironment.java:39)
	at info.ephyra.search.searchers.IndriKM.doSearch(IndriKM.java:200)
	at info.ephyra.search.searchers.Searcher.run(Searcher.java:41)
java.lang.NoClassDefFoundError: Could not initialize class lemurproject.indri.indriJNI
	at lemurproject.indri.QueryEnvironment.<init>(QueryEnvironment.java:39)
	at info.ephyra.search.searchers.IndriKM.doSearch(IndriKM.java:200)
	at info.ephyra.search.searchers.Searcher.run(Searcher.java:41)
java.lang.NoClassDefFoundError: Could not initialize class lemurproject.indri.indriJNI
	at lemurproject.indri.QueryEnvironment.<init>(QueryEnvironment.java:39)
	at info.ephyra.search.searchers.IndriKM.doSearch(IndriKM.java:200)
	at info.ephyra.search.searchers.Searcher.run(Searcher.java:41)
cougar@busdata:~/sirius/sirius-application/run-scripts$ 
```

**Comment by cdmeister** [comment]
Hey, I am using 14.04 but I am using Oracle's Java instead. You should give that a try. Threre is a ppa that can install Oracle's Java 8. I find that Oracle's java generally better in my experience.

**Comment by jbeuckm** [comment]
Thanks, @cdmeister. It worked!
